[package]
org = "ballerinax"
name = "persist.googlesheets"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["persist", "googlesheets", "experimental"]
repository = "https://github.com/ballerina-platform/module-ballerina-persist"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.googlesheets-native"
version = "@toml.version@"
path = "../native/build/libs/persist.googlesheets-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "@persist.version@"
path = "./lib/persist-native-@persist.native.version@.jar"
